Contabilidad/Controllers/FacturacionController.cs
using Contabilidad.Clases;
using Contabilidad.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Contabilidad.Controllers
{
    public class FacturacionController : Controller
    {
        // GET: Facturacion

        string test = ConfigurationManager.AppSettings.Get("test");
        string urlNuevaCotizacion = ConfigurationManager.AppSettings.Get("urlNuevaCotizacion");
        string urlSolicitudes = ConfigurationManager.AppSettings.Get("urlSolicitudes");
        public ActionResult Index()
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");
            return PartialView();
        }

        public ActionResult _GrillaFacturacion(string inicio, string termino, byte idEstado)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");

            int idUsuario = 10088;
            int perfil = 1;
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
                perfil = int.Parse(Request.Cookies["cookiePerfil"]["perfil"].ToString());
            }

            List<Factura> oListaFacturas = new List<Factura>();
            try
            {
                oListaFacturas = FacturacionModel.getFacturacion(idUsuario, inicio, termino, idEstado);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }

            ViewBag.perfil = perfil;
            ViewBag.idUsuario = idUsuario;
            ViewBag.urlNuevaCotizacion = urlNuevaCotizacion;
            ViewBag.urlSolicitudes = urlSolicitudes;
            return PartialView("_GrillaFacturacion", oListaFacturas);
        }

        public string CambiarEstado(string IdsActualizar, int idNuevoEstado)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return "Debe autenticarse en Corretaje.";

            int idUsuario = 10088;
            string mensaje = "";
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }

            try
            {
                mensaje = FacturacionModel.CambiarEstado(idUsuario, IdsActualizar, idNuevoEstado);
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }
            return mensaje;
        }


        public JsonResult FormatosExcel(string grilla)
        {
            int idUsuario = 10088;
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }
            //int usuario = 1;
            //int usuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            return Json(new { resp = FacturacionModel.Llama_GeneraExcelHeader(idUsuario,grilla) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExportarExcel(FormCollection f)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");

            int idUsuario = 10088;
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }

            int idFormato = int.Parse(f["idFormato"].ToString());
            string grilla = f["grilla"].ToString();
            string inicio = f["inicio"].ToString();
            string termino = f["termino"].ToString();
            string fechaContable = f["fechaContable"].ToString();
            int id_estado_facturacion = int.Parse(f["id_estado_facturacion"].ToString()); // en el caso de Pago proveedores, corresponde al estado de pago
            string idsSeleccion = f["ids_seleccion"].ToString();
            int idProveedor = int.Parse(f["id_proveedor"].ToString());


            GridView gv = new GridView();

            gv.DataSource = FacturacionModel.Llama_GeneraExcel(idUsuario, idFormato, grilla, inicio, termino, id_estado_facturacion, fechaContable, idsSeleccion, idProveedor);

            gv.DataBind();

            string nomArchSalida = "Consulta_" + inicio + "_al_" + termino + ".xls";
            switch (idFormato)
            {
                case 1:
                    nomArchSalida = "Interfaz_NUBOX_" + inicio + "_al_" + termino + ".xls";
                    break;
                case 2:
                    nomArchSalida = "Interfaz_Banco_Pagos_" + inicio + "_al_" + termino + ".xls";
                    break;
                case 3:
                    nomArchSalida = "Interfaz_Contable_Pagos_" + inicio + "_al_" + termino + ".xls";
                    break;
                case 4:
                    nomArchSalida = "Interfaz_NUBOX_" + inicio + "_al_" + termino + "_Con_Seleccion.xls";
                    break;
                case 90:
                    nomArchSalida = "Consulta_Facturacion_" + inicio + "_al_" + termino + ".xls";
                    break;
                case 91:
                    nomArchSalida = "Consulta_Pagos_" + inicio + "_al_" + termino + ".xls";
                    break;

            }


            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=" + nomArchSalida);
            Response.ContentType = "application/vnd.ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);

            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();

            return null;
        }


        [HttpPost]
        public ActionResult _FormularioCargaArchivo()
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");
            return PartialView();
        }

        [HttpPost]
        public ActionResult _ResultadoCargarArchivos(HttpPostedFileBase archivo)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");

            List<ListadoCargaFacturas> lst = new List<ListadoCargaFacturas>();

            string rutaSubirFactura = ConfigurationManager.AppSettings.Get("rutaSubirFactura");

            if (!System.IO.Directory.Exists(rutaSubirFactura)) { System.IO.Directory.CreateDirectory(rutaSubirFactura); }

            if (archivo != null && archivo.ContentLength > 0)
            {
                var path = "";
                var nombreArchivo = System.IO.Path.GetFileName(archivo.FileName);
                nombreArchivo = DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + nombreArchivo.Replace(' ', '_');
                path = System.IO.Path.Combine(rutaSubirFactura, nombreArchivo);
                archivo.SaveAs(path);
                List<FacturaCotizacion> listaFacturas = new List<FacturaCotizacion>();
                listaFacturas = LeerPDF(path, rutaSubirFactura);
                foreach (var factura in listaFacturas)
                {
                    lst.Add(new ListadoCargaFacturas
                    {
                        idCotizacion = factura.idCotizacion,
                        id_factura = factura.folioFactura,
                        nombre_cliente = factura.nombreCliente,
                        g_archivo_factura = factura.nombreArchivo,
                        neto = factura.neto.ToString("N0"),
                        iva = factura.iva.ToString("N0"),
                        total = factura.total.ToString("N0")
                    });
                }

                if (System.IO.File.Exists(path))
                    System.IO.File.Delete(path);

                ViewBag.urlSolicitudes = urlSolicitudes;
                return PartialView(lst);
            }
            else
            {
                return PartialView(lst);
            }
        }

        public List<FacturaCotizacion> LeerPDF(object Filename, string directorio_salida)
        {
            int IdUsuario = 10088;
            if (test != "True")
            {
                IdUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }
            List<FacturaCotizacion> lst = new List<FacturaCotizacion>();

            PdfReader reader2 = new PdfReader((string)Filename);

            for (int page = 1; page <= reader2.NumberOfPages; page++)
            {
                ITextExtractionStrategy its = new iTextSharp.text.pdf.parser.SimpleTextExtractionStrategy();
                PdfReader reader = new PdfReader((string)Filename);
                String s = PdfTextExtractor.GetTextFromPage(reader, page, its);

                s = Encoding.UTF8.GetString(ASCIIEncoding.Convert(Encoding.Default, Encoding.UTF8, Encoding.Default.GetBytes(s)));
                System.Diagnostics.Debug.WriteLine(s);
                double esNumero = 0;
                int idCotizacion;

Contabilidad/Views/Facturacion/Index.cshtml
@{
    var meses = new string[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" };
    var diasMeses = new int[] { 0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
    var indiceMes = 1;
    var mesSel = DateTime.Now.Month - 1;
    var anoSel = DateTime.Now.Year;
    if (mesSel == 0)
    {
        mesSel = 12;
        anoSel -= 1;
    }
    if (anoSel % 4 == 0)
    {
        diasMeses[2] = 29;
    }

    var inicio = anoSel.ToString() + "-" + mesSel.ToString() + "-1";
    var termino = anoSel.ToString() + "-" + mesSel.ToString() + "-" + diasMeses[mesSel];


}
<div>
    <div class="" align="center" style="text-align: center; margin-top: 10px;">

        <div class="celda text-right color-corp" style="padding: 0;">Periodicidad: </div>
        <div class="celda text-left " style="font-size: 14px;padding:0; padding-top: 2px;margin-left: 5px; ">
            <input type="radio" name="periodicidad" id="periodicidad" checked value="mes" />&nbsp;Mensual
            <input type="radio" name="periodicidad" id="periodicidad" value="periodo" style="margin-left: 5px;" />&nbsp;Rango fechas
        </div>
        <div class="celda text-left " id="filtroMes" style=" margin-left: 10px">

            <select class="form-control-sm " id="selMes">
                @foreach (var mes in meses)
                {
                    var selected = "";
                    if (mesSel == indiceMes)
                    {
                        selected = "selected";
                    }

                    <option @selected value="@indiceMes">@mes</option>

                    indiceMes += 1;
                }
            </select>
            <select class="form-control-sm " id="selAno">
                @for (var ano = DateTime.Now.Year - 1; ano < DateTime.Now.Year + 2; ano++)
                {
                    var selected = "";
                    if (ano == anoSel)
                    {
                        selected = "selected";
                    }
                    <option @selected value="@ano">@ano</option>
                }

            </select>
        </div>
        <div id="filtroRango" class="celda collapse " style=" padding:0px; font-size: 14px; margin-left:10px;">
            <span class="color-corp">Desde</span>
            <input class="" type="date" id="desde" />&nbsp;&nbsp;
            <span class="color-corp">Hasta</span>
            <input class="" type="date" id="hasta" />
        </div>
        <div id="" class="celda  " style=" padding-left:0px; margin-left: 50px;">
            <select class="form-control-sm" id="estado">
                <option selected value="99">Todos los estados</option>
                <option value="0">Pendiente</option>
                @*<option value="1">Aprobada</option>
                    <option value="2">Rechazada</option>*@
                <option value="9">Facturada</option>
            </select>
        </div>


        <div class="celda" style=" margin-left:20px;">
            <button onclick="buscar()" type="button" class="btn btn-corp CP-BG" style="color: #333;  padding: 5px 20px 5px 30px;">
                <i class="fa fa-search" aria-hidden="true"></i>Buscar
            </button>
        </div>
    </div>

</div>
<div id="GrillaFacturacion" class="mt-3">
    @Html.Action("_GrillaFacturacion", new { inicio = inicio, termino = termino, idEstado = 99 })
</div>


<!-- Modal cargando-->
<div class="modal" id="mdlCargando" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="buttonload text-primary" style="margin: 0 auto;">
                <i class="fa fa-spinner fa-spin "></i>Cargando...
            </div>
        </div>
    </div>
</div>

<script>
    $('[name="periodicidad"]').on('change', function () {
        //alert($(this).val())
        if ($(this).val() === "mes") {
            $('#filtroMes').css("display", "inline-block");
            $('#filtroRango').css("display", "none");
        } else {
            $('#filtroMes').css("display", "none");
            $('#filtroRango').css("display", "inline-block");
        }
    });

    function buscar() {
        $("#mdlCargando").modal();
        var diasMeses = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
        if (parseInt($("#selAno").val()) % 4 == 0) diasMeses[2] = 29;

        if ($("#periodicidad:checked").val() == "mes") {
            inicio = $("#selAno").val() + "-" + $("#selMes").val() + "-" + "1"
            termino = $("#selAno").val() + "-" + $("#selMes").val() + "-" + diasMeses[parseInt($("#selMes").val())]
        } else {
            inicio = $("#desde").val()
            termino = $("#hasta").val()
        }

        estado = $("#estado").val()
        //alert(inicio + " " + termino + " " + estado)


        var url = "@Url.Action("_GrillaFacturacion", "Facturacion")";

        var parametro = {
            "inicio": inicio,
            "termino": termino,
            "idEstado": estado
        };
        $.ajax({
            type: "POST",
            url: url,
            data: parametro,
            async: true,
            success: function (data) {
                $("#GrillaFacturacion").html(data);
                $("#mdlCargando").modal('hide');
            }
        });
    };

</script>

Contabilidad/Views/Facturacion/_FormularioCargaArchivo.cshtml
<style>
    .ImagenesSubir {
        transition: all .5s ease-in-out;
        filter: opacity(.4);
        cursor: pointer;
    }

        .ImagenesSubir:hover {
            transition: all .5s ease-in-out;
            filter: opacity(1);
        }
</style>
<form class="" action="" method="post" name="formulario_add_facturas" id="formulario_add_facturas">
    <div class="" style="text-align: center;" id="icono_carga">
        <br />
        <span style="margin: 50px;">Click en la Imagen para subir archivo PDF.</span>
        <br />
        <br />
        <div class="" align="center">
            <img src="~/img/upload_file_icon.jpg" style="width: 100px; height: 80px; margin:0 auto;" class="ImagenesSubir" /><br />
            <input class="" type="file" id="ArchivoFactura" name="ArchivoFactura" value="" style="visibility: hidden;" />
        </div>
    </div>
    <div id="icono_cargando" style="text-align: center;">
        <br />
        <br />
        <br />
        <br />
        <img src="~/img/cargando.gif" style="width: 100px; height: 100px;" />
    </div>
    <div id="ResultadoDeCarga"></div>
</form>
<script>

    $("#icono_carga").show();
    $("#icono_cargando").hide();

    $(".ImagenesSubir").click(function () {
        $("#icono_carga").hide();
        $("#ArchivoFactura").click();
    });

    $("#ArchivoFactura").change(function () {

        $("#icono_cargando").show();

        var data = new FormData();

        var archivo = $(this).get(0).files;

        if (archivo.length > 0) { data.append("archivo", archivo[0]); }

        var subir2 = $.ajax({
            type: "POST",
            url: "@Url.Action("_ResultadoCargarArchivos", "Facturacion")",
            contentType: false,
            processData: false,
            data: data,
            async: true
        });

        subir2.done(function (xhr, textStatus) {
            $("#icono_cargando").hide();
            $("#ResultadoDeCarga").html(xhr);
        });

    });

</script>

Contabilidad/Views/Facturacion/_ResultadoCargarArchivos.cshtml
@model IEnumerable<Contabilidad.Clases.ListadoCargaFacturas>
@using System.Configuration;

@{
    string DirectorioFacturas = ConfigurationManager.AppSettings.Get("rutaSubirFactura");
}

<style>
    .flota_derecha {
        float: right;
    }
</style>

<table class="table table-striped table-hover table-bordered table-condensed table-responsive" id="tabla_carga">
    <thead>
        <tr>
            <th>Factura</th>
            <th>Cot.</th>
            <th>Nombre Cliente</th>
            <th>Neto</th>
            <th>IVA</th>
            <th>Total</th>
            <th>Ver</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var rutaFacturaArch = ViewBag.urlSolicitudes + "Home/VerArchivo?nombreArchivo=" + @item.g_archivo_factura + "&tipo=6&id=" + @item.idCotizacion;

            <tr>
                <td>@item.id_factura</td>
                <td>@item.idCotizacion</td>
                <td>@item.nombre_cliente</td>
                <td>@item.neto</td>
                <td>@item.iva</td>
                <td>@item.total</td>
                <td><a href="@rutaFacturaArch" target="_blank">PDF</a></td>
            </tr>
        }
    </tbody>
</table>
<script>
    $("#tabla_carga").dataTable({
        dom: 'B<"flota_derecha"lf>rtip',
        buttons: [
            {
                extend: 'excelHtml5',
                text: 'Excel',
                footer: true,
                exportOptions: {
                    columns: ':visible'
                },
                filename: 'CargaDeFacturas.xlsx'
            },
            {
                extend: 'pdfHtml5',
                orientation: 'landscape',
                pageSize: 'LEGAL',
                text: 'PDF',
                footer: true,
                exportOptions: {
                    columns: ':visible'
                },
                filename: 'CargaDeFacturas.pdf'
            }
        ]
    });
</script>