Contabilidad/Controllers/PagosController.cs
using Contabilidad.Clases;
using Contabilidad.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Contabilidad.Controllers
{
    public class PagosController : Controller
    {
        // GET: Pagos
        string test = ConfigurationManager.AppSettings.Get("test");
        string urlCotizaciones = ConfigurationManager.AppSettings.Get("urlCotizaciones");
        string urlMantenedores = ConfigurationManager.AppSettings.Get("urlMantenedores");
        string urlEnEjecucion = ConfigurationManager.AppSettings.Get("urlEnEjecucion");
        string urlSolicitudes = ConfigurationManager.AppSettings.Get("urlSolicitudes");

        public ActionResult Index()
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");
            return PartialView();
        }

        public ActionResult _ListaComboBox()
        {
            return PartialView();
        }
        public ActionResult _GrillaPagos(string inicio, string termino, byte idEstado, int idProveedor = 0, int tipo_proveedor = 0)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");

            int idUsuario = 10088;
            int perfil = 1;
            int idArea = 3;

            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
                perfil = int.Parse(Request.Cookies["cookiePerfil"]["perfil"].ToString());
                idArea = int.Parse(Request.Cookies["cookiePerfil"]["idArea"].ToString());
            }

            List<Pago> oListaPagos = new List<Pago>();
            try
            {
                oListaPagos = PagosModel.getPagosProveedores(idUsuario, inicio, termino, idEstado, idProveedor, tipo_proveedor);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }

            ViewBag.perfil = perfil;
            ViewBag.idUsuario = idUsuario;
            ViewBag.idArea = idArea;
            ViewBag.urlCotizaciones = urlCotizaciones;
            ViewBag.urlMantenedores = urlMantenedores;
            ViewBag.urlEnEjecucion = urlEnEjecucion;
            ViewBag.urlSolicitudes = urlSolicitudes;
            return PartialView("_GrillaPagos", oListaPagos);
        }


        public string CambiarEstadoPago(string IdsActualizar, int idNuevoEstado, string fechaNomina)
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return "Debe autenticarse en Corretaje.";

            int idUsuario = 10088;
            string mensaje = "";
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }

            try
            {
                mensaje = PagosModel.CambiarEstado(idUsuario, IdsActualizar, idNuevoEstado, fechaNomina);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }
            return mensaje;
        }


        public ActionResult _BancoCuenta()
        {
            if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) return Content("Debe autenticarse en Corretaje.");

            int idUsuario = 10088;
            if (test != "True")
            {
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            }

            ViewBag.urlCotizaciones = urlCotizaciones;
            ViewBag.urlMantenedores = urlMantenedores;
            return PartialView("_BancoCuenta");
        }


        public ActionResult _ObservacionesPago(int idTipo, int idAsignacion, string numFactura, string nomProveedor)
        {
            int idUsuario = 10088;
            if (test != "True")
                idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
            PagoObservaciones oPagoObs = new PagoObservaciones();
            try
            {
                oPagoObs = PagosModel.getPagosObservaciones(idUsuario, idTipo, idAsignacion);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }
            ViewBag.urlSolicitudes = urlSolicitudes;
            ViewBag.idAsignacion = idAsignacion;
            ViewBag.numFactura = numFactura;
            ViewBag.nomProveedor = nomProveedor;
            return PartialView("_ObservacionesPago", oPagoObs);
        }


        public string _GuardarObservacion(int idTipo, int idAsignacion, string obs)
        {
            int idUsuario = 10088;
            if (test != "True") idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());

            string mensaje = "";
            if (obs.Trim() == "")
            {
                mensaje = "Debe ingresar una observación";
            }
            else
            {
                try
                {
                    mensaje = PagosModel.addObservacion(idUsuario, idTipo, idAsignacion, obs);
                }
                catch (Exception ex)
                {
                    mensaje = "Error:" + ex.Message;
                }
            }
            return mensaje;
        }

        public ActionResult _ListaProveedores()
        {
            int idUsuario = 10088;
            if (test != "True") idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());

            List<Proveedor> oListaProveedores = new List<Proveedor>();
            try
            {
                oListaProveedores = PagosModel.getListaProveedores(idUsuario);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error:" + ex.Message;
            }
            return PartialView("_ListaProveedores", oListaProveedores);
        }
    }
}

Contabilidad/Views/Pagos/Index.cshtml
@using System.Configuration;

@{
    var meses = new string[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" };
    var diasMeses = new int[] { 0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
    var indiceMes = 1;
    var mesSel = DateTime.Now.Month - 1;
    var anoSel = DateTime.Now.Year;
    if (mesSel == 0)
    {
        mesSel = 12;
        anoSel -= 1;
    }
    if (anoSel % 4 == 0)
    {
        diasMeses[2] = 29;
    }

    var inicio = anoSel.ToString() + "-" + mesSel.ToString() + "-1";
    var termino = anoSel.ToString() + "-" + mesSel.ToString() + "-" + diasMeses[mesSel];

    int idUsuario = 10088;

    string test = ConfigurationManager.AppSettings.Get("test");
    if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null)) 
    {
        idUsuario = 0;
    };


    if (test != "True")
    {
        idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
    }
    }
<div>
    <div class="" align="center" style="text-align: center; margin-top: 10px;">

        <div class="celda text-right color-corp" style="padding: 0;">Periodicidad: </div>
        <div class="celda text-left " style="font-size: 14px;padding:0; padding-top: 2px;margin-left: 5px; ">
            <input type="radio" name="periodicidadPago" id="periodicidadPago" checked value="mes" />&nbsp;Mensual
            <input type="radio" name="periodicidadPago" id="periodicidadPago" value="periodo" style="margin-left: 5px;" />&nbsp;Rango fechas
        </div>
        <div class="celda text-left " id="filtroMesPago" style=" margin-left: 10px">

            <select class="form-control-sm " id="selMesPago">
                @foreach (var mes in meses)
                {
                    var selected = "";
                    if (mesSel == indiceMes)
                    {
                        selected = "selected";
                    }

                    <option @selected value="@indiceMes">@mes</option>

                    indiceMes += 1;
                }
            </select>
            <select class="form-control-sm " id="selAnoPago">
                @for (var ano = DateTime.Now.Year - 1; ano < DateTime.Now.Year + 2; ano++)
                {
                    var selected = "";
                    if (ano == anoSel)
                    {
                        selected = "selected";
                    }
                    <option @selected value="@ano">@ano</option>
                }

            </select>
        </div>
        <div id="filtroRangoPago" class="celda collapse " style=" padding:0px; font-size: 14px; margin-left:10px;">
            <span class="color-corp">Desde</span>
            <input class="" type="date" id="desdePago" />&nbsp;&nbsp;
            <span class="color-corp">Hasta</span>
            <input class="" type="date" id="hastaPago" />
        </div>
        <div class="celda m-2">
            <div id="" style="">
                @Html.Action("_ListaProveedores")

            </div>

        </div>
        <div id="" class="celda" style=" padding-left:0px; margin-left: 10px;">
            <select class="form-control-sm" id="estadoPago">
                <option selected value="99">Todos los estados</option>
                <option value="0">Pendiente</option>
                <option value="3">Solicitado</option>
                <option value="1">Aprobado</option>
                <option value="2">Rechazado</option>
                <option value="9">Pagado</option>
            </select>
        </div>

        <div class="celda" style=" padding-left:0px; margin-left: 10px;">
            <select class="form-control-sm" id="tipoProv">
                <option value="0" selected>Todos los proveedores</option>
                @Html.Partial("_ListaComboBox", Contabilidad.Models.PagosModel.Llama_core_cargar_lista(idUsuario, 199, "C"))
            </select>
        </div>

        <div class="celda" style=" margin-left:20px;">
            <button onclick="buscarPago()" type="button" class="btn btn-corp CP-BG" style="color: #333;  padding: 5px 20px 5px 30px;" ">
                <i class="fa fa-search" aria-hidden="true"></i>Buscar
            </button>
        </div>
    </div>

</div>
<div id="GrillaPagos" class="mt-3">
    @Html.Action("_GrillaPagos", new { inicio = inicio, termino = termino, idEstado = 99, idProveedor = 0 , tipo_proveedor = (idUsuario == 60329 ? 2: (idUsuario == 60320 ? 1 : 0)) })
</div>



<script>
    $(document).ready(function () {
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

    });

    $('[name="periodicidadPago"]').on('change', function () {
        //alert($(this).val())
        if ($(this).val() === "mes") {
            $('#filtroMesPago').css("display", "inline-block");
            $('#filtroRangoPago').css("display", "none");
        } else {
            $('#filtroMesPago').css("display", "none");
            $('#filtroRangoPago').css("display", "inline-block");
        }
    });

    function buscarPago() {
        var diasMeses = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
        if (parseInt($("#selAnoPago").val()) % 4 == 0) diasMeses[2] = 29;

        if ($("#periodicidadPago:checked").val() == "mes") {
            inicio = $("#selAnoPago").val() + "-" + $("#selMesPago").val() + "-" + "1"
            termino = $("#selAnoPago").val() + "-" + $("#selMesPago").val() + "-" + diasMeses[parseInt($("#selMesPago").val())]
        } else {
            inicio = $("#desdePago").val()
            termino = $("#hastaPago").val()
        }

        estado = $("#estadoPago").val()
        idProveedor = $("#SelProveedor").val()
        //alert(inicio + " " + termino + " " + estado)
        tipo_proveedor = $('#tipoProv').val()

        var url = "@Url.Action("_GrillaPagos", "Pagos")";

        var parametro = {
            "inicio": inicio,
            "termino": termino,
            "idProveedor": idProveedor,
            "idEstado": estado,
            "tipo_proveedor": tipo_proveedor
        };
        $.ajax({
            type: "POST",
            url: url,
            data: parametro,
            async: true,
            success: function (data) {
                $("#GrillaPagos").html(data);
            }
        });
    };

</script>

Contabilidad/Views/Pagos/_BancoCuenta.cshtml
<div class="modal fade" id="ModalBancoCuenta" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable " role="document">
        <div class="modal-content ">
            <div class="modal-header US-8">

                <h6 class="modal-title"><i class="fas fa-landmark mr-2"></i>Cuenta de Depósito</h6>
                <button type="button" class="close" data-dismiss="modal" style="color:#fff;">&times;</button>

            </div>
            <div class="modal-body text-left scrollbar ">
                <div class="row m-4">
                    <input type="text" class="form-control" id="RutCta" placeholder="Rut Cuenta" onblur="formato_rut(this)" />
                </div>
                <div class="row m-4">
                    <input type="text" class="form-control" id="NombreCta" placeholder="Nombre" />
                </div>
                <div class="row m-4" id="divBanco"></div>
                <div class="row m-4" id="divTipoCuenta"></div>
                <div class="row m-4">
                    <input type="text" class="form-control" id="NumeroCta" placeholder="Número de Cuenta" />
                </div>
                <div id="msjErrorBcoCta" class="alert alert-danger collapse" role="alert">
                    This is a danger alert—check it out!
                </div>
                <div class="mx-auto text-center">
                    <input type="hidden" id="idProveedor" />
                    <a href="javascript:void(0)" class="btn btn-corp US-8 m-2" data-dismiss="modal" arial-label="close">cancelar</a>
                    <a href="javascript:void(0)" class="btn btn-corp m-2 GuardarBcoCta"><i class="fas fa-save mr-2"></i>Guardar</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {
        CargaListaBanco()
        CargaListaTipoCuenta()
    });

    function CargaListaBanco() {
        var url = "@ViewBag.urlCotizaciones" + "/home/_CargaListaGeneral";
        var parametro = {
            "idTabla": 25,
            "idKey": "c_item",
            "orden": "G",
            "textoOpcionCero": "Banco",
            "nomInput": "Banco"
        };

        $.ajax({
            type: "POST",
            url: url,
            data: parametro,
            async: true,
            success: function (data) {
                $("#divBanco").html(data);
            }
        });
    }

    function CargaListaTipoCuenta() {
        var url = "@ViewBag.urlCotizaciones" + "/home/_CargaListaGeneral";
        var parametro = {
            "idTabla": 68,
            "idKey": "c_item",
            "orden": "G",
            "textoOpcionCero": "Tipo de cuenta",
            "nomInput": "TipoCta"
        };

        $.ajax({
            type: "POST",
            url: url,
            data: parametro,
            async: true,
            success: function (data) {
                $("#divTipoCuenta").html(data);
            }
        });
    }

    $(".GuardarBcoCta").click(function () {
        $("#msjErrorBcoCta").hide()
        if ($("#RutCta").val() == "") {
            $("#msjErrorBcoCta").html("Debe ingresar el rut de la cuenta").show()
            $("#RutCta").focus();
            return false;
        }
        if ($("#NombreCta").val() == "") {
            $("#msjErrorBcoCta").html("Debe ingresar el nombre de la cuenta").show()
            $("#NombreCta").focus();
            return false;
        }
        if ($("#Banco").val() == "0") {
            $("#msjErrorBcoCta").html("Debe seleccionar banco").show()
            $("#Banco").focus();
            return false;
        }
        if ($("#TipoCta").val() == "0") {
            $("#msjErrorBcoCta").html("Debe seleccionar el tipo de cuenta").show()
            $("#TipoCta").focus();
            return false;
        }
        if ($("#NumeroCta").val() == "") {
            $("#msjErrorBcoCta").html("Debe ingresar el número de la cuenta").show()
            $("#NumeroCta").focus();
            return false;
        }

        var param = {
            "idProveedor": $("#idProveedor").val()
            , "rutCta": $("#RutCta").val()
            , "nomCta": $("#NombreCta").val()
            , "idBanco": $("#Banco").val()
            , "idTipoCta": $("#TipoCta").val()
            , "numeroCta": $("#NumeroCta").val()
        };
        var url = "@ViewBag.urlMantenedores" + "/Proveedores/GuardarCtaDeposito";
        $.ajax({
            type: "POST",
            url: url,
            data: param,
            async: false,
            success: function (Ok) {
                if (Ok) {
                    alert("Cuenta guardarda")
                    $("#ModalBancoCuenta").modal('hide');
                    $('.modal-backdrop').hide();
                    buscarPago();


                } else {
                    alert("Error al guardar cuenta");
                }
            }
        });

    });

    function formato_rut(rut) {
        $("#msjErrorBcoCta").html("");
        $("#msjErrorBcoCta").fadeOut();
        var rut_aux = rut.value

        var rut_aux = rut_aux.replace(/\./g, "");
        rut_aux = rut_aux.replace(/-/g, "");
        rut.value = rut_aux

        var sRut1 = rut.value;      //contador de para saber cuando /img/ar el . o la -
        var nPos = 0;               //Guarda el rut invertido con los puntos y el guión agregado
        var sInvertido = "";        //Guarda el resultado final del rut como debe ser
        var sRut = "";
        for (var i = sRut1.length - 1; i >= 0; i--) {
            sInvertido += sRut1.charAt(i);
            if (i == sRut1.length - 1)
                sInvertido += "-";
            else if (nPos == 3) {
                sInvertido += ".";
                nPos = 0;
            }
            nPos++;
        }
        for (var j = sInvertido.length - 1; j >= 0; j--) {
            if (sInvertido.charAt(sInvertido.length - 1) != ".")
                sRut += sInvertido.charAt(j);
            else if (j != sInvertido.length - 1)
                sRut += sInvertido.charAt(j);
        }
        //Pasamos al campo el valor formateado
        rut.value = sRut.toUpperCase();
        if (!valida_rut(rut.value)) {
            $("#msjErrorBcoCta").html("Rut ingresado no válido.");
            $("#msjErrorBcoCta").fadeIn();
            $("#RutCta").focus();
        }
    }

    function valida_rut(rut) {
        var rut_aux = rut.replace(/\./g, "");
        rut_aux = rut_aux.replace(/-/g, "");
        rut = rut_aux
        //Valor acumulado para el calculo de la formula
        var nAcumula = 0;
        //Factor por el cual se debe multiplicar el valor de la posicion
        var nFactor = 2;
        //Dígito verificador
        var nDv = 0;
        //extraemos el ultimo numero o letra que corresponde al verificador
        //La K corresponde a 10
        if (rut.charAt(rut.length - 1).toUpperCase() == 'K')
            nDvReal = 10;
        //el 0 corresponde a 11
        else if (rut.charAt(rut.length - 1) == 0)
            nDvReal = 11;
        else
            nDvReal = rut.charAt(rut.length - 1);

        for (nPos = rut.length - 2; nPos >= 0; nPos--) {
            nAcumula += rut.charAt(nPos).valueOf() * nFactor;
            nFactor++;
            if (nFactor > 7) nFactor = 2;
        }


        nDv = 11 - (nAcumula % 11)
        if (nDv == nDvReal)
            return true;
        return false;
    }

</script>

Contabilidad/Views/Pagos/_ListaComboBox.cshtml
@model IEnumerable<Contabilidad.Clases.listascombobox>
@using System.Configuration;
@{ int idUsuario = 10088;

    string test = ConfigurationManager.AppSettings.Get("test");
    if (test != "True" && (Request.Cookies["cookiePerfil"] == null || Request.Cookies["cookiePerfil"]["usuario"] == null))
    {
        idUsuario = 0;
    };


    if (test != "True")
    {
        idUsuario = int.Parse(Request.Cookies["cookiePerfil"]["usuario"].ToString());
    }
}
@foreach (var item in Model)
{
    <option value="@item.id" @(idUsuario == 60329 && item.id == 2 ? "selected": (idUsuario == 60320 && item.id == 1 ? "selected" : ""))>@item.descripcion</option>
}

Contabilidad/Views/Pagos/_ListaProveedores.cshtml
<select class="form-control-sm" id="SelProveedor" style="width: 200px;">
    <option value="0">Todos los Proveedores</option>
    @foreach (var prv in Model)
    {
        <option value="@prv.idProveedor">@prv.nombreProveedor</option>
    }
</select>

Contabilidad/Views/Pagos/_ObservacionesPago.cshtml
<!-- Modal: Observaciones Solicitud -->

<div class="modal fade" id="ModalPagoObs" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header US-8">
                <h6 class="modal-title"><i class="fab fa-font-awesome-flag mr-2"></i>Observaciones Pago Factura N° @ViewBag.numFactura</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" style="color:white;">×</span>
                </button>
            </div>
            <div class="modal-body text-left">
                <div class="alert alert-danger text-center " role="alert" id="msjError" style="display: none;">
                    This is a danger alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
                </div>
                <table class="table table-borderless">
                    <thead>
                        <tr>
                            <th class="USL-8">Proveedor</th>
                            <td>@ViewBag.nomProveedor</td>
                        </tr>
                        <tr>
                            <th class="USL-8">N° Factura</th>
                            <td>@ViewBag.numFactura</td>
                        </tr>
                    </thead>
                </table>

                <form class="mx-auto text-center">
                    <textarea class="form-control" placeholder="Observación" id="fObs" rows="5"></textarea>
                    <a href="" class="btn US-8 m-4" data-dismiss="modal" arial-label="close">cancelar</a>
                    <a href="#" onclick="guardar()" class="btn btn-corp m-4" style="padding: 11px 40px;"><i class="fas fa-save mr-2"></i>Guardar</a>
                </form>
                <h6 class="USL-8 mt-3 mb-4">Historial de observaciones</h6><!--Mostrar y guardar las últimas 10-->
                <table class="table shadow-sm mt-2 text-center" style="font-size: 12px;">
                    <thead>
                        <tr>
                            <th class="brl" style="text-align: left;">Fecha</th>
                            <th style="text-align: left;">Usuario</th>
                            <th class="brr">Observación</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.observaciones.Count == 0)
                        {
                            <tr>
                                <td colspan="3"><strong>Sin Observaciones</strong></td>
                            </tr>
                        }

                        @foreach (var obs in Model.observaciones)
                        {
                            <tr>
                                <td>@obs.fecha</td>
                                <td>@obs.nomUsuario</td>
                                <td>@obs.observaciones</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Modal: Guardar -->
<div class="modal fade" id="MsSave" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body text-center" id="">
                La información se ha guardado con éxito.
            </div>
        </div>
    </div>
</div>



<script>
    function guardar() {
        $("#msjError").fadeOut();
        var url = "@Url.Action("_GuardarObservacion", "Pagos")";
        var parametro = {
            "idTipo": 1,        // observación pago de factura
            "idAsignacion": @ViewBag.idAsignacion,
            "obs": $("#fObs").val()
        };

        $.ajax({
            type: "POST",
            url: url,
            data: parametro,
            async: true,
            success: function (mensaje) {
                if (mensaje == "") {
                    $('#ModalPagoObs').modal('hide');
                    $("#MsSave").modal();
                } else {
                    $("#msjError").html(mensaje);
                    $("#msjError").fadeIn();
                }
            }
        });


    };




</script>